-- ============================================================================
-- TAFA (Tourism AI for Arequipa) - Clean Production-Ready MVP Schema
-- Ecosistema Nacional de Turismo Inteligente (PostgreSQL + PostGIS)
-- 17 Tablas | Sin accesibilidad (gestionada por otro equipo)
-- ============================================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. PROFILES (Usuarios y Turistas)
CREATE TABLE IF NOT EXISTS profiles (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email               TEXT UNIQUE NOT NULL,
  full_name           TEXT NOT NULL,
  doc_type            TEXT DEFAULT 'DNI',
  doc_number          TEXT,
  tafa_explorer_pass  TEXT UNIQUE NOT NULL,
  points_earned       INTEGER DEFAULT 100,
  visited_places      INTEGER DEFAULT 0,
  favorite_category   TEXT,
  preferred_language  TEXT DEFAULT 'espanol',
  last_trip           DATE,
  trip_days           INTEGER DEFAULT 3,
  travel_style        TEXT DEFAULT 'cultural',
  role                TEXT DEFAULT 'tourist',
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TRAVEL_PROFILES
CREATE TABLE IF NOT EXISTS travel_profiles (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  profile_id          UUID REFERENCES profiles(id) ON DELETE CASCADE,
  origin_country      TEXT DEFAULT 'Peru',
  origin_city         TEXT,
  arrival_date        DATE,
  departure_date      DATE,
  budget_amount       NUMERIC(10,2) DEFAULT 0.0,
  travel_type         TEXT DEFAULT 'solo',
  lodging_type        TEXT,
  transport_type      TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 3. DISTRICTS
CREATE TABLE IF NOT EXISTS districts (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                TEXT NOT NULL UNIQUE,
  province            TEXT DEFAULT 'Arequipa',
  region              TEXT DEFAULT 'Arequipa',
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CATEGORIES
CREATE TABLE IF NOT EXISTS categories (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                TEXT NOT NULL UNIQUE,
  slug                TEXT NOT NULL UNIQUE,
  description         TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 5. PLACES (Atractivos Turisticos)
CREATE TABLE IF NOT EXISTS places (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                TEXT NOT NULL UNIQUE,
  category_id         BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  district_id         BIGINT REFERENCES districts(id) ON DELETE SET NULL,
  description         TEXT,
  lat                 DOUBLE PRECISION,
  lng                 DOUBLE PRECISION,
  geom                GEOMETRY(Point, 4326),
  address             TEXT,
  opening_hours       TEXT,
  admission_fee       TEXT,
  official_source     TEXT DEFAULT 'MINCETUR',
  is_verified         BOOLEAN DEFAULT TRUE,
  is_unexplored       BOOLEAN DEFAULT FALSE,
  points_reward       INTEGER DEFAULT 50,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_places_geom ON places USING GIST (geom);

-- 6. PLACE_MEDIA
CREATE TABLE IF NOT EXISTS place_media (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  place_id            BIGINT REFERENCES places(id) ON DELETE CASCADE,
  media_type          TEXT DEFAULT 'image',
  url                 TEXT NOT NULL,
  caption             TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 7. ROUTES (Rutas Turisticas)
CREATE TABLE IF NOT EXISTS routes (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name                TEXT NOT NULL,
  summary             TEXT NOT NULL,
  duration_hours      NUMERIC(4,1) DEFAULT 4.0,
  difficulty_level    TEXT DEFAULT 'moderada',
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 8. ROUTE_PLACES
CREATE TABLE IF NOT EXISTS route_places (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  route_id            UUID REFERENCES routes(id) ON DELETE CASCADE,
  place_id            BIGINT REFERENCES places(id) ON DELETE CASCADE,
  step_order          INTEGER NOT NULL,
  recommendation_note TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 9. BUSINESS_CATEGORIES
CREATE TABLE IF NOT EXISTS business_categories (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                TEXT NOT NULL UNIQUE,
  description         TEXT
);

-- 10. BUSINESSES (Ecosistema de Negocios Aliados)
CREATE TABLE IF NOT EXISTS businesses (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tax_id              TEXT UNIQUE,
  business_name       TEXT NOT NULL,
  trade_name          TEXT NOT NULL,
  category_id         BIGINT REFERENCES business_categories(id) ON DELETE SET NULL,
  district_id         BIGINT REFERENCES districts(id) ON DELETE SET NULL,
  address             TEXT,
  phone               TEXT,
  email               TEXT,
  website             TEXT,
  lat                 DOUBLE PRECISION,
  lng                 DOUBLE PRECISION,
  status              TEXT DEFAULT 'aliado',
  rating_score        NUMERIC(3,2) DEFAULT 4.80,
  complaints_count    INTEGER DEFAULT 0,
  dircetur_badge      BOOLEAN DEFAULT TRUE,
  price_range         TEXT DEFAULT 'medio',
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 11. REWARDS (Sistema "Discover More")
CREATE TABLE IF NOT EXISTS rewards (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  business_id         UUID REFERENCES businesses(id) ON DELETE CASCADE,
  title               TEXT NOT NULL,
  experience_details  TEXT NOT NULL,
  required_points     INTEGER NOT NULL CHECK(required_points > 0),
  is_active           BOOLEAN DEFAULT TRUE,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 12. USER_REWARDS
CREATE TABLE IF NOT EXISTS user_rewards (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  profile_id          UUID REFERENCES profiles(id) ON DELETE CASCADE,
  reward_id           UUID REFERENCES rewards(id) ON DELETE CASCADE,
  redemption_code     TEXT NOT NULL,
  status              TEXT DEFAULT 'unlocked',
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 13. ITINERARIES
CREATE TABLE IF NOT EXISTS itineraries (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  profile_id          UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title               TEXT NOT NULL,
  days_count          INTEGER DEFAULT 3,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 14. REVIEWS
CREATE TABLE IF NOT EXISTS reviews (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  profile_id          UUID REFERENCES profiles(id) ON DELETE SET NULL,
  place_id            BIGINT REFERENCES places(id) ON DELETE CASCADE,
  rating              INTEGER CHECK(rating BETWEEN 1 AND 5),
  comment             TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 15. APPLICATIONS (Join TAFA Ecosystem - Postulaciones MYPE)
CREATE TABLE IF NOT EXISTS applications (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tax_id              TEXT NOT NULL,
  company_name        TEXT NOT NULL,
  contact_email       TEXT NOT NULL,
  contact_phone       TEXT NOT NULL,
  category            TEXT NOT NULL,
  district            TEXT NOT NULL,
  status              TEXT DEFAULT 'pending',
  notes               TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 16. SYSTEM_SETTINGS
CREATE TABLE IF NOT EXISTS system_settings (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key         TEXT UNIQUE NOT NULL,
  setting_value       TEXT NOT NULL,
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 17. ACCESSIBILITY_PREFERENCES (Reservada para otro equipo)
CREATE TABLE IF NOT EXISTS accessibility_preferences (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  profile_id          UUID REFERENCES profiles(id) ON DELETE CASCADE UNIQUE,
  notes               TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- DATOS SEMILLA - DISTRITOS DE AREQUIPA
-- ============================================================================

INSERT INTO districts (name, province, region) VALUES
('Cercado', 'Arequipa', 'Arequipa'),
('Yanahuara', 'Arequipa', 'Arequipa'),
('Cayma', 'Arequipa', 'Arequipa'),
('Paucarpata', 'Arequipa', 'Arequipa'),
('Sabandia', 'Arequipa', 'Arequipa'),
('Cerro Colorado', 'Arequipa', 'Arequipa'),
('Jose Luis Bustamante y Rivero', 'Arequipa', 'Arequipa'),
('Socabaya', 'Arequipa', 'Arequipa'),
('Miraflores', 'Arequipa', 'Arequipa'),
('Mariano Melgar', 'Arequipa', 'Arequipa'),
('Selva Alegre', 'Arequipa', 'Arequipa'),
('Tiabaya', 'Arequipa', 'Arequipa'),
('Sachaca', 'Arequipa', 'Arequipa'),
('Hunter', 'Arequipa', 'Arequipa'),
('Chivay', 'Caylloma', 'Arequipa'),
('Yanque', 'Caylloma', 'Arequipa'),
('Cabanaconde', 'Caylloma', 'Arequipa'),
('Corire', 'Castilla', 'Arequipa'),
('Cotahuasi', 'La Union', 'Arequipa'),
('Andagua', 'Castilla', 'Arequipa'),
('Mollendo', 'Islay', 'Arequipa'),
('Mejia', 'Islay', 'Arequipa'),
('Camana', 'Camana', 'Arequipa')
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- DATOS SEMILLA - CATEGORIAS
-- ============================================================================

INSERT INTO categories (name, slug, description) VALUES
('Patrimonio Historico', 'patrimonio', 'Monumentos, casonas coloniales, catedrales e iglesias'),
('Naturaleza y Aventura', 'naturaleza', 'Canones, reservas naturales, volcanes y lagunas'),
('Centro Historico', 'centro-historico', 'Monasterios, plazas y arquitectura de sillar'),
('Gastronomia', 'gastronomia', 'Picanterias, restaurantes y comida regional'),
('Ruta Inexplorada', 'inexploradas', 'Canteras, petroglifos y destinos alternativos'),
('Hospedaje', 'hospedaje', 'Hoteles, hostales, albergues y casas rurales'),
('Mirador y Paisaje', 'miradores', 'Miradores naturales y panoramicos'),
('Termalismo', 'termalismo', 'Banos termales y aguas medicinales'),
('Cultura Viva', 'cultura-viva', 'Festividades, danzas y tradiciones locales'),
('Compras y Artesania', 'compras', 'Mercados, talleres artesanales y souvenirs')
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- DATOS SEMILLA - LUGARES TURISTICOS (Variedad completa)
-- ============================================================================

INSERT INTO places (name, description, lat, lng, address, opening_hours, admission_fee, official_source, is_verified, is_unexplored, points_reward) VALUES
-- Centro Historico y Patrimonio
('Plaza de Armas de Arequipa', 'Plaza principal rodeada de arquerias de sillar volcanico y la Catedral neoclasica del siglo XVII. Declarada Patrimonio de la Humanidad por UNESCO.', -16.3988, -71.5369, 'Plaza de Armas s/n, Cercado', '24 horas', 'Acceso Libre', 'DIRCETUR', TRUE, FALSE, 50),
('Basilica Catedral de Arequipa', 'Catedral neoclasica construida en sillar blanco, alberga el organo belga mas grande de Sudamerica. Museo interior con arte sacro colonial.', -16.3989, -71.5372, 'Plaza de Armas s/n, Cercado', '10:00 - 17:00', 'S/ 15.00', 'MINCETUR', TRUE, FALSE, 60),
('Monasterio de Santa Catalina', 'Ciudadela monastica de 20,000 m2 con claustros tenidos de azul anil y rojo terracota. Fundado en 1579, funciono como ciudad independiente.', -16.3953, -71.5367, 'Calle Santa Catalina 301, Cercado', '09:00 - 17:00', 'S/ 45.00', 'MINCETUR', TRUE, FALSE, 80),
('Iglesia de la Compania de Jesus', 'Joya del barroco mestizo arequipeno. Fachada tallada en sillar con motivos indigenas y europeos. Claustros con arcos y pintura mural.', -16.3996, -71.5360, 'General Moran 118, Cercado', '09:00 - 12:30 / 15:00 - 18:00', 'S/ 5.00', 'MINCETUR', TRUE, FALSE, 55),
('Barrio de San Lazaro', 'Primer barrio de Arequipa fundado en el siglo XVI. Callejuelas empedradas, plazoletas y casonas coloniales de sillar blanco.', -16.3940, -71.5355, 'Barrio San Lazaro, Cercado', '24 horas', 'Acceso Libre', 'DIRCETUR', TRUE, FALSE, 40),
('Mansion del Fundador', 'Casona colonial del siglo XVIII atribuida al fundador de Arequipa, Garcia Manuel de Carbajal. Jardin con vista al rio Socabaya.', -16.4300, -71.4900, 'Huasacache, Hunter', '09:00 - 17:00', 'S/ 20.00', 'DIRCETUR', TRUE, FALSE, 55),
('Iglesia y Convento de Santo Domingo', 'Uno de los primeros templos de Arequipa. Portada renacentista en sillar con campanario que domina el centro historico.', -16.3970, -71.5340, 'Calle Santo Domingo 103, Cercado', '07:00 - 12:00 / 16:00 - 19:00', 'Acceso Libre', 'MINCETUR', TRUE, FALSE, 40),
('Museo Santuarios Andinos (Juanita)', 'Museo de la Universidad Catolica Santa Maria que exhibe a la Dama de Ampato, momia inca de mas de 500 anos encontrada en el Ampato.', -16.3975, -71.5340, 'Calle La Merced 110, Cercado', '09:00 - 18:00', 'S/ 20.00', 'MINCETUR', TRUE, FALSE, 70),
('Museo de Arte Virreinal de Santa Teresa', 'Antiguo monasterio carmelita con coleccion de arte sacro virreinal, pintura cusquena y objetos liturgicos de los siglos XVI al XIX.', -16.3965, -71.5385, 'Calle Melgar 303, Cercado', '09:00 - 17:00', 'S/ 10.00', 'MINCETUR', TRUE, FALSE, 50),

-- Miradores y Paisajes
('Mirador de Yanahuara', 'Arcos de sillar tallados con versos de poetas arequipenos. Vista panoramica del volcan Misti y la ciudad desde la plaza del distrito.', -16.3881, -71.5422, 'Plaza de Yanahuara', '24 horas', 'Acceso Libre', 'Municipalidad Yanahuara', TRUE, FALSE, 40),
('Mirador de Carmen Alto', 'Terraza natural con vista al valle de Chilina, las andenerias prehispanicas y los volcanes Misti, Chachani y Pichu Pichu.', -16.3830, -71.5450, 'Carmen Alto, Cayma', '24 horas', 'Acceso Libre', 'Municipalidad Cayma', TRUE, FALSE, 35),
('Mirador de Sachaca', 'Vista panoramica sobre los andenes de Chilina y la campina arequipena. Zona tranquila fuera del circuito turistico principal.', -16.3950, -71.5550, 'Sachaca', '24 horas', 'Acceso Libre', 'DIRCETUR', TRUE, TRUE, 35),

-- Naturaleza y Aventura
('Canon del Colca', 'Uno de los canones mas profundos del mundo con 3,400 metros. Avistamiento de condores andinos en Cruz del Condor. Pueblos coloniales a lo largo del valle.', -15.6386, -71.9022, 'Valle del Colca, Caylloma', '05:00 - 17:00', 'Boleto Turistico S/ 70', 'AUTOCOLCA', TRUE, FALSE, 100),
('Volcan Misti', 'Estratovolcan activo de 5,822 msnm, simbolo de Arequipa. Ascenso de 2 dias para montanistas intermedios y avanzados.', -16.2942, -71.4090, 'Cordillera Volcanica, Arequipa', 'Requiere guia', 'S/ 50.00 (permiso SERNANP)', 'SERNANP', TRUE, FALSE, 120),
('Reserva Nacional Salinas y Aguada Blanca', 'Area protegida de 366,936 ha. Habitat de vicunas, alpacas y flamencos. Lagunas de Salinas con bofedales y paisaje altoandiino.', -16.2083, -71.2134, 'Carretera Arequipa-Puno', '06:00 - 16:00', 'Acceso Libre', 'SERNANP', TRUE, TRUE, 85),
('Laguna de Salinas', 'Laguna salada a 4,300 msnm al pie del Pichu Pichu. Habitat de flamencos altoandinos y aves migratorias. Paisaje desertico lunar.', -16.3500, -71.1300, 'Ruta Arequipa-Puno km 80', '06:00 - 16:00', 'Acceso Libre', 'SERNANP', TRUE, TRUE, 75),
('Catarata de Pillones', 'Caida de agua de 30 metros en un paisaje de ichu y bofedales a 4,400 msnm. Acceso desde la carretera a Puno. Caminata corta.', -15.8200, -71.2500, 'Ruta Arequipa-Chivay km 120', 'Horario natural', 'Acceso Libre', 'DIRCETUR', TRUE, TRUE, 65),
('Bosque de Piedras de Imata', 'Formaciones rocosas naturales de origen volcanico a 4,500 msnm que semejan un bosque petrificado. Paisaje surrealista.', -15.8400, -71.0800, 'Pampa de Arrieros, Imata', 'Horario natural', 'Acceso Libre', 'DIRCETUR', TRUE, TRUE, 60),

-- Rutas Inexploradas
('Ruta del Sillar - Anashuayco', 'Canteras activas donde artesanos esculpen a mano la piedra volcanica blanca que construyo la ciudad. Recorrido guiado por las quebradas.', -16.3572, -71.5908, 'Cerro Colorado', '08:00 - 16:30', 'S/ 5.00', 'DIRCETUR', TRUE, TRUE, 60),
('Petroglifos de Toro Muerto', 'Mas de 5,000 bloques volcanicos grabados con arte rupestre pre-Inca. Uno de los sitios de arte rupestre mas grandes del mundo.', -16.2234, -72.4831, 'Corire, Valle de Majes', '08:00 - 16:00', 'S/ 10.00', 'MINCETUR', TRUE, TRUE, 90),
('Valle de los Volcanes de Andagua', 'Paisaje geologico unico con mas de 80 conos volcanicos extintos, coladas de lava y lagunas en la cuenca del rio Andagua.', -15.4900, -72.3500, 'Andagua, Castilla', 'Horario natural', 'Acceso Libre', 'DIRCETUR', TRUE, TRUE, 95),
('Canon de Cotahuasi', 'El canon mas profundo del Peru con 3,535 metros. Cataratas, aguas termales, ruinas incas y pueblos aislados. Destino de trekking avanzado.', -15.2100, -72.8900, 'Cotahuasi, La Union', 'Horario natural', 'Acceso Libre', 'DIRCETUR', TRUE, TRUE, 100),
('Cuevas de Sumbay', 'Abrigos rocosos con pinturas rupestres de 8,000 anos de antiguedad. Representaciones de camelidos, cazadores y escenas de la vida diaria.', -15.9800, -71.3600, 'Reserva Salinas y Aguada Blanca', '08:00 - 16:00', 'Incluido en boleto RNSAB', 'SERNANP', TRUE, TRUE, 70),

-- Termalismo
('Banos Termales La Calera (Chivay)', 'Piscinas de aguas termales entre 35 y 40 grados con vista al canon y montanas nevadas. Acceso desde Chivay.', -15.6330, -71.5990, 'Chivay, Caylloma', '05:00 - 19:00', 'S/ 20.00', 'AUTOCOLCA', TRUE, FALSE, 55),
('Banos Termales de Yanque', 'Aguas termomedicinales a orillas del rio Colca. Menos turistico que La Calera, ambiente mas tranquilo y natural.', -15.6550, -71.6600, 'Yanque, Caylloma', '06:00 - 18:00', 'S/ 15.00', 'AUTOCOLCA', TRUE, FALSE, 50),
('Banos Termales de Yura', 'Fuentes termales historicas a 30 km de Arequipa ciudad. Cuatro pozas con distintas temperaturas y propiedades minerales.', -16.2500, -71.6800, 'Yura, Arequipa', '06:00 - 18:00', 'S/ 5.00', 'DIRCETUR', TRUE, FALSE, 40),

-- Costa de Arequipa
('Playas de Mejia y Mollendo', 'Balnearios costeros de la provincia de Islay. Playas de arena, paseo maritimo y gastronomia marina. Temporada de enero a marzo.', -17.0240, -72.0100, 'Mollendo - Mejia, Islay', '24 horas', 'Acceso Libre', 'DIRCETUR', TRUE, FALSE, 50),
('Santuario Nacional Lagunas de Mejia', 'Humedal costero protegido de 690 ha. Habitat de 195 especies de aves, incluyendo migratorias de Norteamerica. Avistamiento con binoculares.', -17.1100, -71.8600, 'Mejia, Islay', '07:00 - 16:00', 'S/ 5.00', 'SERNANP', TRUE, FALSE, 60),

-- Cultura Viva
('Molino de Sabandia', 'Arquitectura colonial de 1621 que aun muele grano usando la fuerza del agua. Jardines con camellidos y vista a la campina.', -16.4478, -71.4922, 'Sabandia', '09:00 - 17:00', 'S/ 10.00', 'DIRCETUR', TRUE, FALSE, 50),
('Mundo Alpaca', 'Centro interpretativo sobre camelidos sudamericanos. Exhibicion de alpacas, vicunas y llamas. Demostracion de hilado y tejido artesanal.', -16.3900, -71.5380, 'Calle Jerusalem 600, Cercado', '09:00 - 17:30', 'Acceso Libre', 'Privado', TRUE, FALSE, 35)
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- DATOS SEMILLA - CATEGORIAS DE NEGOCIO
-- ============================================================================

INSERT INTO business_categories (name, description) VALUES
('Hospedaje - Hotel', 'Hoteles de 1 a 5 estrellas con servicios completos'),
('Hospedaje - Hostal', 'Hostales y albergues economicos para viajeros'),
('Hospedaje - Casa Rural', 'Alojamiento rural y experiencias vivenciales en comunidades'),
('Restaurante - Picanteria', 'Picanterias tradicionales arequipenas con comida regional'),
('Restaurante - Gourmet', 'Restaurantes de autor y cocina contemporanea arequipena'),
('Restaurante - Cafe', 'Cafeterias, juguerias y brunch con productos locales'),
('Restaurante - Comida Rapida', 'Establecimientos de comida rapida y street food'),
('Tour Operador', 'Agencias de turismo y operadores certificados por DIRCETUR'),
('Transporte Turistico', 'Servicios de transporte turistico terrestre y aereo'),
('Artesania y Souvenirs', 'Talleres y tiendas de artesania local, textiles y ceramica'),
('Entretenimiento', 'Bares, penas folcloricas y centros de entretenimiento'),
('Spa y Bienestar', 'Centros de bienestar, masajes y tratamientos con productos andinos')
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- DATOS SEMILLA - NEGOCIOS ALIADOS (Restaurantes, Hostales, Tours)
-- ============================================================================

INSERT INTO businesses (tax_id, business_name, trade_name, address, phone, status, rating_score, dircetur_badge, price_range) VALUES
-- Picanterias Tradicionales
('20100001001', 'Picanteria La Lucila S.A.C.', 'La Lucila', 'Calle Grau 204, Sachaca', '054-221234', 'aliado', 4.90, TRUE, 'medio'),
('20100001002', 'Picanteria La Capitana E.I.R.L.', 'La Capitana', 'Calle Dolores 309, Jose Luis Bustamante y Rivero', '054-223456', 'aliado', 4.85, TRUE, 'medio'),
('20100001003', 'Picanteria Sol de Mayo S.R.L.', 'Sol de Mayo', 'Calle Jerusalem 207, Yanahuara', '054-225678', 'aliado', 4.88, TRUE, 'medio-alto'),
('20100001004', 'Picanteria La Nueva Palomino S.A.C.', 'La Nueva Palomino', 'Calle Leoncio Prado 122, Yanahuara', '054-227890', 'aliado', 4.82, TRUE, 'medio'),
('20100001005', 'Picanteria La Benita E.I.R.L.', 'La Benita', 'Calle Misti 108, Sachaca', '054-229012', 'aliado', 4.75, TRUE, 'economico'),

-- Restaurantes Gourmet y Contemporaneos
('20100002001', 'Zig Zag Restaurant S.A.C.', 'Zig Zag', 'Calle Zela 210, Cercado', '054-206020', 'aliado', 4.92, TRUE, 'alto'),
('20100002002', 'Salamanto Restaurante S.A.C.', 'Salamanto', 'Calle San Francisco 223, Cercado', '054-201145', 'aliado', 4.78, TRUE, 'alto'),
('20100002003', 'Chicha por Gaston Acurio S.A.C.', 'Chicha Arequipa', 'Calle Santa Catalina 210, Cercado', '054-287360', 'aliado', 4.85, TRUE, 'alto'),
('20100002004', 'Crepisimo Restaurant S.R.L.', 'Crepisimo', 'Calle Santa Catalina 208, Cercado', '054-202090', 'aliado', 4.60, TRUE, 'medio'),
('20100002005', 'Hatunpa Restaurant S.A.C.', 'Hatunpa', 'Calle Ugarte 208, Cercado', '054-213898', 'aliado', 4.70, TRUE, 'medio'),

-- Cafeterias
('20100003001', 'Cafe Valenzuela S.A.C.', 'Cafe Valenzuela', 'Calle San Francisco 125, Cercado', '054-235011', 'aliado', 4.50, TRUE, 'medio'),
('20100003002', 'Capriccio Pasteleria S.R.L.', 'Capriccio', 'Calle Mercaderes 121, Cercado', '054-214477', 'aliado', 4.55, TRUE, 'medio'),

-- Hoteles
('20200001001', 'Casa Andina Premium Arequipa S.A.', 'Casa Andina Premium', 'Calle Ugarte 403, Cercado', '054-202070', 'aliado', 4.75, TRUE, 'alto'),
('20200001002', 'Sonesta Posada del Inca S.A.', 'Sonesta Arequipa', 'Portal de Flores 116, Cercado', '054-215530', 'aliado', 4.65, TRUE, 'alto'),
('20200001003', 'Hotel Libertador Arequipa S.A.', 'Libertador Arequipa', 'Plaza Bolivar s/n, Selva Alegre', '054-215110', 'aliado', 4.80, TRUE, 'alto'),
('20200001004', 'Katari Hotel at Plaza de Armas S.A.C.', 'Katari Hotel', 'Calle San Agustin 231, Cercado', '054-202992', 'aliado', 4.70, TRUE, 'alto'),

-- Hostales
('20200002001', 'Hostal Solar S.R.L.', 'Hostal Solar', 'Calle Ayacucho 108, Cercado', '054-241793', 'aliado', 4.40, TRUE, 'economico'),
('20200002002', 'Los Tambos Hostal E.I.R.L.', 'Los Tambos', 'Calle Bolognesi 229, Cercado', '054-213932', 'aliado', 4.45, TRUE, 'economico'),
('20200002003', 'Wild Rover Hostel Arequipa S.A.C.', 'Wild Rover Arequipa', 'Calle Rivero 209, Cercado', '054-206552', 'aliado', 4.35, FALSE, 'economico'),
('20200002004', 'Flying Dog Hostel S.A.C.', 'Flying Dog', 'Calle Jerusalem 516, Cercado', '054-201454', 'aliado', 4.30, FALSE, 'economico'),

-- Hostales en el Colca
('20200003001', 'Colca Lodge Spa and Hot Springs S.A.C.', 'Colca Lodge', 'Fundo Puye s/n, Yanque', '054-202587', 'aliado', 4.85, TRUE, 'alto'),
('20200003002', 'Hotel Pozo del Cielo E.I.R.L.', 'Pozo del Cielo', 'Calle Bolognesi s/n, Chivay', '054-531045', 'aliado', 4.50, TRUE, 'medio'),

-- Tour Operadores
('20300001001', 'Giardino Tours S.A.C.', 'Giardino Tours', 'Calle Santa Catalina 500, Cercado', '054-200100', 'aliado', 4.70, TRUE, 'medio'),
('20300001002', 'Pablo Tour S.R.L.', 'Pablo Tour', 'Calle Jerusalem 400, Cercado', '054-203737', 'aliado', 4.60, TRUE, 'medio'),
('20300001003', 'Santa Catalina Tours E.I.R.L.', 'SC Tours', 'Calle Santa Catalina 223, Cercado', '054-216994', 'aliado', 4.55, TRUE, 'medio'),
('20300001004', 'Colonial Tours Peru S.A.C.', 'Colonial Tours', 'Calle Puente Bolivar 114, Cercado', '054-286868', 'aliado', 4.50, TRUE, 'medio'),

-- Artesania
('20400001001', 'Fundo El Fierro - Centro Artesanal S.A.C.', 'Fundo El Fierro', 'Calle Zela 201, Cercado', '054-283331', 'aliado', 4.40, TRUE, 'economico'),
('20400001002', 'Patio del Ekeko Artesanias S.R.L.', 'Patio del Ekeko', 'Calle Mercaderes 141, Cercado', '054-215861', 'aliado', 4.45, TRUE, 'medio')
ON CONFLICT (tax_id) DO NOTHING;

-- ============================================================================
-- DATOS SEMILLA - RUTAS TURISTICAS
-- ============================================================================

INSERT INTO routes (name, summary, duration_hours, difficulty_level) VALUES
('Centro Historico Clasico', 'Recorrido por la Plaza de Armas, Catedral, Monasterio de Santa Catalina, Iglesia de la Compania y barrio San Lazaro. Ideal para un primer dia en Arequipa.', 4.0, 'facil'),
('Ruta de los Volcanes', 'Ascenso al Misti o visita al Chachani. Para montanistas con experiencia. Incluye aclimatacion en la Reserva Salinas y Aguada Blanca.', 24.0, 'dificil'),
('Valle del Colca - 2 dias', 'Viaje de 2 dias al Canon del Colca: Chivay, banos termales La Calera, Cruz del Condor, pueblos de Yanque y Cabanaconde.', 48.0, 'moderada'),
('Ruta de las Picanterias', 'Tour gastronomico por las picanterias tradicionales de Arequipa: La Lucila, Sol de Mayo, La Nueva Palomino. Incluye degustacion de chicha de guinapo.', 5.0, 'facil'),
('Ruta del Sillar', 'Visita a las canteras de sillar de Anashuayco. Ver artesanos tallando la piedra volcanica blanca que dio fama a la Ciudad Blanca.', 3.5, 'moderada'),
('Arequipa Nocturna', 'Paseo por el centro historico iluminado, cena en restaurante de autor, visita a pena folclorica con musica y danzas tradicionales.', 4.0, 'facil'),
('Campiña y Miradores', 'Recorrido por los miradores de Yanahuara, Carmen Alto y Sachaca. Incluye visita al Molino de Sabandia y andenerias de Chilina.', 5.0, 'facil'),
('Toro Muerto y Valle de Majes', 'Excursion al valle de Majes: petroglifos de Toro Muerto, deportes de aventura en el rio Majes, y gastronomia de camarones.', 12.0, 'moderada'),
('Cotahuasi Extremo - 4 dias', 'Trekking al canon mas profundo del Peru. Cataratas, aguas termales, ruinas incas y comunidades aisladas. Solo para aventureros.', 96.0, 'dificil'),
('Costa de Arequipa', 'Viaje a Mollendo y Mejia: playas, Santuario Nacional Lagunas de Mejia, gastronomia marina y paseo por el malecon.', 12.0, 'facil')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- DATOS SEMILLA - REWARDS (Discover More)
-- ============================================================================

INSERT INTO system_settings (setting_key, setting_value) VALUES
('platform_name', 'TAFA - Tourism AI for Arequipa'),
('platform_version', 'MVP 1.0'),
('default_language', 'es'),
('points_per_visit', '50'),
('points_per_review', '25'),
('points_per_referral', '100'),
('max_daily_points', '500'),
('support_email', 'soporte@tafa.pe')
ON CONFLICT (setting_key) DO NOTHING;

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE places ENABLE ROW LEVEL SECURITY;
ALTER TABLE routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Places" ON places FOR SELECT USING (TRUE);
CREATE POLICY "Public Read Routes" ON routes FOR SELECT USING (TRUE);
CREATE POLICY "Public Read Businesses" ON businesses FOR SELECT USING (TRUE);
CREATE POLICY "Public Read Business Categories" ON business_categories FOR SELECT USING (TRUE);
CREATE POLICY "Public Read Categories" ON categories FOR SELECT USING (TRUE);
CREATE POLICY "Public Read Districts" ON districts FOR SELECT USING (TRUE);
CREATE POLICY "Public Insert Applications" ON applications FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Public Read Route Places" ON route_places FOR SELECT USING (TRUE);
CREATE POLICY "Public Read Place Media" ON place_media FOR SELECT USING (TRUE);
CREATE POLICY "Public Read System Settings" ON system_settings FOR SELECT USING (TRUE);

-- ============================================================================
-- FIN DEL SCHEMA MVP TAFA
-- 17 tablas | 30+ lugares | 28+ negocios | 10 rutas | 23 distritos
-- ============================================================================
